const data = {
    products: [
      {
        name: 'H&M-slim-fit-shirt',
        slug: 'H&M-slim-fit-shirt',
        category: 'Shirts',
        image: '/images/61ecbuT3TnL._UY550_.jpg', 
        price: 15 ,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'H&M-shirt',
        slug: 'H&M-shirt',
        category: 'Shirts',
        image: '/images/pants.jpg', 
        price: 20,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'vintage dress',
        slug: 'vintage dress',
        category: 'dress',
        image: '/images/pngegg (5).png', 
        price: 80,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'feminin dress',
      },
      {
        name: 'short dress and shirt with stripes',
        slug: 'short dress and shirt with stripes',
        category: 'couples',
        image: '/images/419-Xw21ibL.jpg', 
        price: 40,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'feminin dress',
      },
      {
        name: ' dress ',
        slug: ' dress',
        category: 'dress',
        image: '/images/pngegg (1).png', 
        price: 40,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'feminin dress',
      },
      {
        name: 'short dress ',
        slug: 'short dress',
        category: 'dress',
        image: '/images/pngegg (7).png', 
        price: 40,
        countInStock: 1,
        brand: 'H&M',
        numReviews: 10,
        description: 'feminin dress',
      },
      {
      name: 'shirts',
      slug: 'shirts',
      category: 'package',
      image: '/images/Shirts.jpg', 
      price: 40,
      countInStock: 3,
      brand: 'zara',
      numReviews: 10,
      description: 'matching fit',
    },
    ],
  };
  export default data;